# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2ddb1390038931e5bedd9f5918beccd1f144a75035a2211eaa3fd2758401aae0f2f533bd5edc6a91561cb708b57a582e904269836da53638913af0c21d5273

test:
  secret_key_base: 16aec7e407ecc083e684d6c8a11873bcfd4dcd0e7a0e738d29f1f73dacb3bcab0e02e44c1b19a2e51da2143011c8a03507290196f5674471b8c18b4c4e3c2c24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
